frontend:
  apiHost: "http://kind.community.taraxa.io"
  imagePullSecrets:
    - name: taraxaregistry
  image:
    repository: gcr.io/jovial-meridian-249123/taraxa-community-frontend-develop
    tag: "latest"

  nodeSelector:
    cloud.google.com/gke-nodepool: taraxa-community-kind

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: kind.community.taraxa.io
  tls: []

